# Change these first
owner: abteilung # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Abteilung.ch
    url: https://abteilung.ch
  - name: Aarvia AG
    url: https://aarvia.ch
  - name: Ades.ch
    url: https://ades.ch
  - name: All in One VT
    url: https://allinone-vt.ch
  - name: Auf Sicher CH
    url: https://auf-sicher.ch
  - name: Ally.Vision
    url: https://ally.vision
  - name: My.Ally.Vision
    url: https://my.ally.vision
  - name: Auf Sicher Swiss
    url: https://auf-sicher.swiss
  - name: Baerlocher Legate
    url: https://baerlocher-legate.ch
  - name: Barcli Hotels
    url: https://barclihotels.com
  - name: Barcli Hospitality
    url: https://barclihospitality.com
  - name: BETM
    url: https://betm.ch
  - name: Bonnie & Clyde
    url: https://bonnie-and-clyde.com
  - name: BVI AG (Domain bviag.ch)
    url: http://bviag.ch
  - name: BVI AG
    url: http://bvi-innenausbau.ch
  - name: Communtia
    url: https://communtia.ch
  - name: Daniel Brüngger
    url: https://danielbruengger.ch
  - name: Der Baumpfleger
    url: https://derbaumpfleger.ch
  - name: Die Coacherei
    url: https://die-coacherei.ch
  - name: DSIM
    url: https://dsim.ch
  - name: Dunedin Arts
    url: https://dunedin-arts.ch
  - name: ELK
    url: http://elk.ie
  - name: EAO
    url: https://eao.com
  - name: EBC Brugg
    url: https://ebc-brugg.ch
  - name: Elternverein Meilen
    url: https://elternvereinmeilen.ch
  - name: Elternverein Rüschlikon
    url: https://elternverein-rueschlikon.ch
  - name: Eweco
    url: https://eweco.ch
  - name: Ferienwohnugn Vazerol
    url: https://ferienwohnungvazerol.com
  - name: Folienmaster
    url: https://folienmaster.ch
  - name: Furore Kanalservice
    url: https://furore.gmbh
  - name: Forum Pfarrblatt
    url: https://forum-pfarrblatt.ch
  - name: Gees Metall
    url: https://geesmetall.ch
  - name: Green Drains
    url: https://green-drains.ch
  - name: Hand Dryer
    url: https://handdryer.com
  - name: Heryanora
    url: https://heryanora.com
  - name: Hoffmann Coaching
    url: https://hoffmanncoaching.ch
  - name: Humid-or
    url: https://humid-or.ch
  - name: Immobilien 4 you
    url: https://immobilien4you.ch
  - name: Immobilienwelten
    url: https://immobilienwelten.ch
  - name: Isenbügel
    url: https://isenbuegel.ch
  - name: Kiwanis Höngg
    url: https://kiwanis-hoengg.ch
  - name: Landolf & Huber Juweliere
    url: https://landolfhuber.ch
  - name: Lesen & Schreiben Bern
    url: https://lesenschreiben-bern.ch/
  - name: Licht-Raum
    url: https://licht-raum.ch/
  - name: Linguaprima
    url: https://linguaprima.ch
  - name: Lyner Haustechnik AG
    url: https://lyner-haustechnik.ch/
  - name: Macun CP
    url: https://macuncp.ch
  - name: Matthias Lebo
    url: https://matthiaslebo.com
  - name: Mikro Repro
    url: https://mikrorepro.ch
  - name: Neuezeit Akademie
    url: https://neuezeit-akademie.swiss
  - name: Pfaller AG
    url: https://pfaller.ch
  - name: Physio-Burgernziel
    url: https://physio-burgernziel.ch
  - name: Physiotherapiewissenschaften
    url: https://physiotherapiewissenschaften.ch
  - name: Polydesign 3D
    url: https://p3d.ch    
  - name: Ramseier Assoc
    url: https://ramseier-assoc.com
  - name: Re-Medium
    url: https://re-medium.ch
  - name: Roger Hoch
    url: http://rogerhoch-zahnarzt.ch
  - name: Ruggli Partner
    url: https://rugglipartner.ch
  - name: Rychiger AG
    url: https://rychiger.ch
  - name: Schweizer Röntgen
    url: https://schweizer-roentgen.ch
  - name: Selfix AG
    url: https://selfix.ch
  - name: Sommeliers Choice
    url: https://sommeliers-choice.ch
  - name: Staub KG
    url: https://staubkg.com
  - name: Stefan Ackermann
    url: https://stefanackermann.ch
  - name: Stephen Gould
    url: https://stephengould.org
  - name: Stolkin
    url: https://stolkin.ch
  - name: Swiss CCS
    url: https://swissccs.com
  - name: SGUV
    url: https://sguv.ch
  - name: TM Bachmann
    url: https://tm-bachmann.ch
  - name: Urimat
    url: https://urimat.ch
  - name: Urimat COM
    url: https://urimat.com
  - name: Urimat DE
    url: https://urimat.de
  - name: Urimat ES
    url: https://urimat.es
  - name: Urimat PT
    url: https://urimat.pt
  - name: Valentin-Tools LI
    url: https://valentin-tools.li
  - name: Wernis Team
    url: https://wernisteam.ch
  - name: Wichser Partner
    url: https://wichser-partner.ch
  - name: Wikipick
    url: https://wikipick.ch
  - name: Wini
    url: https://wini.ch
  - name: Wipswiss
    url: https://wipswiss.ch
  - name: Zweidler
    url: https://2dler.ch    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** Website Status Monitor."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
